// Generated by LiveScript 1.5.0
/**
 * @package Detox nodes manager
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  function Wrapper(detoxUtils, asyncEventer){
    /**
     * @constructor
     *
     *
     * @return {!Manager}
     */
    function Manager(){
      if (!(this instanceof Manager)) {
        return new Manager();
      }
      asyncEventer.call(this);
    }
    Manager.prototype = Object.assign(Object.create(asyncEventer.prototype), Manager.prototype);
    Object.defineProperty(Manager.prototype, 'constructor', {
      value: Manager
    });
    return {
      'Manager': Manager
    };
  }
  if (typeof define === 'function' && define['amd']) {
    define(['@detox/utils', 'async-eventer'], Wrapper);
  } else if (typeof exports === 'object') {
    module.exports = Wrapper(require('@detox/utils'), require('async-eventer'));
  } else {
    this['detox_core'] = Wrapper(this['detox_utils'], this['async_eventer']);
  }
}).call(this);
